version: "3.2"
services:
  nginx:
    image: nginx
    ports:
      - "3334:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

  flask:
    build:
      dockerfile: Dockerfile1
      context: .
    command: python main.py 
    ports:
      - "80:5000"
    depends_on:
      - mongodb
    volumes:
      - ./src:/usr/src/app/
    restart: always
          
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
      - ./dump:/dump
    ports:
      - "27017:27017"
      
volumes:
  mongodata:
  